#
# SPDX-FileCopyrightText: © Fossology contributors
#
# SPDX-License-Identifier: FSFAP
#
images:
  web:
    repository: fossology/fossology
    tag: latest
    pullPolicy: IfNotPresent
  worker:
    repository: fossology/fossology-worker
    tag: latest
    pullPolicy: IfNotPresent

repoPersistence:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-rwx

web:
  replicas: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

workers:
  replicas: 4

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: fossology.example.com
      paths:
        - path: /
          pathType: Prefix
